// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAf3Vd836oEt2fzSzc6JTKX2M6W0NlRyCE',
    appId: '1:1044394586117:web:6511d94f66d3fa9f812c6c',
    messagingSenderId: '1044394586117',
    projectId: 'student-task-manager-b0f05',
    authDomain: 'student-task-manager-b0f05.firebaseapp.com',
    storageBucket: 'student-task-manager-b0f05.firebasestorage.app',
    measurementId: 'G-3BM000LSSR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClDKWoHSPVzjUO6mDR9oKq1aag4Ks_A_4',
    appId: '1:1044394586117:android:41f42d92bacfc85c812c6c',
    messagingSenderId: '1044394586117',
    projectId: 'student-task-manager-b0f05',
    storageBucket: 'student-task-manager-b0f05.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQ8oHpjGBcd4EXlevrd4_0JgPt-gHaPSI',
    appId: '1:1044394586117:ios:54e9ed6316fdf01a812c6c',
    messagingSenderId: '1044394586117',
    projectId: 'student-task-manager-b0f05',
    storageBucket: 'student-task-manager-b0f05.firebasestorage.app',
    iosBundleId: 'com.example.studentTaskManagerApp',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQ8oHpjGBcd4EXlevrd4_0JgPt-gHaPSI',
    appId: '1:1044394586117:ios:54e9ed6316fdf01a812c6c',
    messagingSenderId: '1044394586117',
    projectId: 'student-task-manager-b0f05',
    storageBucket: 'student-task-manager-b0f05.firebasestorage.app',
    iosBundleId: 'com.example.studentTaskManagerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAf3Vd836oEt2fzSzc6JTKX2M6W0NlRyCE',
    appId: '1:1044394586117:web:e493977cce3c5f4e812c6c',
    messagingSenderId: '1044394586117',
    projectId: 'student-task-manager-b0f05',
    authDomain: 'student-task-manager-b0f05.firebaseapp.com',
    storageBucket: 'student-task-manager-b0f05.firebasestorage.app',
    measurementId: 'G-GZPFBHZW0W',
  );
}
