// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzUFkYVt2umlpbuikt4mXwKTNEeqWC38I',
    appId: '1:1046543232533:web:33ea2d7893a852051ca81c',
    messagingSenderId: '1046543232533',
    projectId: 'batch-17-604d8',
    authDomain: 'batch-17-604d8.firebaseapp.com',
    storageBucket: 'batch-17-604d8.firebasestorage.app',
    measurementId: 'G-HX3PXL7ZXS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHREj3Y9HgNauiatpZlr4Inl2dzg44Ous',
    appId: '1:1046543232533:android:ad87433818b45aaa1ca81c',
    messagingSenderId: '1046543232533',
    projectId: 'batch-17-604d8',
    storageBucket: 'batch-17-604d8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDW3WWHHJu8EBmno4ICUUDsnGW2qxvVFo0',
    appId: '1:1046543232533:ios:cd3740c663a7c26f1ca81c',
    messagingSenderId: '1046543232533',
    projectId: 'batch-17-604d8',
    storageBucket: 'batch-17-604d8.firebasestorage.app',
    iosClientId: '1046543232533-ai0r2dml0d2is6ms74efpal6s1fodgjp.apps.googleusercontent.com',
    iosBundleId: 'com.example.studentTaskManagerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDW3WWHHJu8EBmno4ICUUDsnGW2qxvVFo0',
    appId: '1:1046543232533:ios:cd3740c663a7c26f1ca81c',
    messagingSenderId: '1046543232533',
    projectId: 'batch-17-604d8',
    storageBucket: 'batch-17-604d8.firebasestorage.app',
    iosClientId: '1046543232533-ai0r2dml0d2is6ms74efpal6s1fodgjp.apps.googleusercontent.com',
    iosBundleId: 'com.example.studentTaskManagerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDzUFkYVt2umlpbuikt4mXwKTNEeqWC38I',
    appId: '1:1046543232533:web:1f2beb8f3ceec4751ca81c',
    messagingSenderId: '1046543232533',
    projectId: 'batch-17-604d8',
    authDomain: 'batch-17-604d8.firebaseapp.com',
    storageBucket: 'batch-17-604d8.firebasestorage.app',
    measurementId: 'G-VVMZZMPSQK',
  );
}
